"""Signal analysis API endpoints."""

from typing import Optional
from fastapi import APIRouter, Query

from ..rtl_manager import rtl_manager
from ..protocols import (
    PROTOCOLS,
    PROTOCOL_CATEGORIES,
    PROGRAM_FLAGS,
    get_protocols_by_category,
    search_protocols,
)

router = APIRouter(prefix="/signals", tags=["signals"])


@router.post("/analyze")
async def analyze_signals(
    duration: int = Query(10, ge=5, le=60, description="Analysis duration in seconds"),
):
    """Run signal analysis mode to detect unknown signals."""
    if rtl_manager.is_running:
        return {
            "error": "Cannot analyze while rtl_433 is running. Stop it first.",
            "hint": "POST /api/v1/system/rtl433/stop"
        }

    results = await rtl_manager.analyze_signal(duration=duration)

    return {
        "duration": duration,
        "signals_detected": len(results),
        "signals": results,
    }


@router.get("/protocols")
async def get_protocols(
    category: Optional[str] = Query(None, description="Filter by category"),
    search: Optional[str] = Query(None, description="Search by name"),
):
    """Get list of all 291 supported protocols."""
    if search:
        protocols = search_protocols(search)
    elif category:
        by_category = get_protocols_by_category()
        protocols = by_category.get(category, [])
    else:
        protocols = PROTOCOLS

    return {
        "protocols": protocols,
        "count": len(protocols),
        "total": len(PROTOCOLS),
    }


@router.get("/protocols/categories")
async def get_protocol_categories():
    """Get list of protocol categories."""
    by_category = get_protocols_by_category()
    categories = [
        {
            "id": cat_id,
            "name": cat_name,
            "count": len(by_category.get(cat_id, []))
        }
        for cat_id, cat_name in PROTOCOL_CATEGORIES.items()
    ]
    return {"categories": categories}


@router.get("/protocols/grouped")
async def get_protocols_grouped():
    """Get protocols grouped by category."""
    by_category = get_protocols_by_category()
    return {
        "categories": PROTOCOL_CATEGORIES,
        "protocols": by_category,
        "total": len(PROTOCOLS),
    }


@router.get("/flags")
async def get_program_flags():
    """Get all available rtl_433 program flags."""
    return {
        "flags": PROGRAM_FLAGS,
        "count": len(PROGRAM_FLAGS),
    }


@router.get("/frequencies")
async def get_frequencies():
    """Get common frequencies for different regions."""
    frequencies = [
        {"frequency": "433.92M", "region": "Europe/Asia", "common_uses": "Weather stations, sensors, remotes"},
        {"frequency": "315M", "region": "North America", "common_uses": "Car remotes, garage doors"},
        {"frequency": "868M", "region": "Europe", "common_uses": "Smart home, meters"},
        {"frequency": "915M", "region": "North America", "common_uses": "Smart meters, LoRa"},
        {"frequency": "345M", "region": "North America", "common_uses": "Security systems"},
        {"frequency": "300M", "region": "Various", "common_uses": "Low frequency sensors"},
        {"frequency": "310M", "region": "Asia", "common_uses": "Car remotes"},
        {"frequency": "390M", "region": "Various", "common_uses": "Specialized sensors"},
        {"frequency": "418M", "region": "Various", "common_uses": "Industrial sensors"},
        {"frequency": "904.6M", "region": "North America", "common_uses": "Utility meters (hopping)"},
    ]

    return {"frequencies": frequencies, "count": len(frequencies)}


@router.post("/config/generate")
async def generate_config(
    protocols: list[int] = Query(default=[], description="Protocol IDs to enable"),
    frequency: str = Query(default="433.92M", description="Receive frequency"),
    sample_rate: str = Query(default="1024k", description="Sample rate"),
    gain: int = Query(default=40, ge=0, le=50, description="Tuner gain"),
    output_json: bool = Query(default=True, description="Enable JSON output"),
    output_mqtt: bool = Query(default=False, description="Enable MQTT output"),
    mqtt_host: str = Query(default="localhost", description="MQTT broker host"),
):
    """Generate rtl_433 configuration based on selected options."""
    config_lines = [
        "# RTL-433 Configuration",
        "# Generated by RTL-SDR Dashboard",
        "",
        f"frequency {frequency}",
        f"sample_rate {sample_rate}",
        f"gain {gain}",
        "",
        "# Unit conversion",
        "convert si",
        "",
    ]

    if output_json:
        config_lines.append("output json")

    if output_mqtt:
        config_lines.append(f"output mqtt://{mqtt_host}:1883,events=rtl_433/events")

    if protocols:
        config_lines.append("")
        config_lines.append("# Enabled protocols")
        for proto_id in sorted(protocols):
            # Find protocol name
            proto = next((p for p in PROTOCOLS if p["id"] == proto_id), None)
            if proto:
                config_lines.append(f"protocol {proto_id}  # {proto['name']}")
            else:
                config_lines.append(f"protocol {proto_id}")
    else:
        config_lines.append("")
        config_lines.append("# Enable all protocols")
        config_lines.append("# protocol all")

    return {
        "config": "\n".join(config_lines),
        "protocols_enabled": len(protocols),
    }
