"""RTL-433 Protocol definitions and program flags."""

from typing import List, Dict, Any

# Protocol categories for filtering
PROTOCOL_CATEGORIES = {
    "temperature": "Temperature Sensors",
    "humidity": "Humidity Sensors",
    "weather": "Weather Stations",
    "tpms": "Tire Pressure Monitors",
    "security": "Security/Alarm Systems",
    "remote": "Remote Controls",
    "power": "Power Meters",
    "water": "Water Meters",
    "smoke": "Smoke/Fire Detectors",
    "doorbell": "Doorbells",
    "automotive": "Automotive",
    "appliance": "Appliances",
    "other": "Other Devices",
}

# RTL-433 supported protocols (extracted from source)
# Format: (id, name, category, description)
PROTOCOLS: List[Dict[str, Any]] = [
    {"id": 1, "name": "Silvercrest Remote Control", "category": "remote", "desc": "Remote control"},
    {"id": 2, "name": "Rubicson, TFA 30.3197 Temperature Sensor", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 3, "name": "Prologue, FreeTec NC-7104", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 4, "name": "Waveman Switch Transmitter", "category": "remote", "desc": "Switch transmitter"},
    {"id": 5, "name": "Steffen Switch Transmitter", "category": "remote", "desc": "Switch transmitter"},
    {"id": 6, "name": "ELV EM 1000", "category": "power", "desc": "Energy monitor"},
    {"id": 7, "name": "ELV WS 2000", "category": "weather", "desc": "Weather station"},
    {"id": 8, "name": "LaCrosse TX Temperature/Humidity", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 9, "name": "Acurite 896 Rain Gauge", "category": "weather", "desc": "Rain gauge"},
    {"id": 10, "name": "Acurite 609TXC Temperature/Humidity", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 11, "name": "Acurite 592TXR/5n1/Atlas Weather", "category": "weather", "desc": "Weather station, temp/humidity"},
    {"id": 12, "name": "Oregon Scientific Weather", "category": "weather", "desc": "Weather station"},
    {"id": 13, "name": "Mebus 433", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 14, "name": "Intertechno 433", "category": "remote", "desc": "Remote switch"},
    {"id": 15, "name": "KlikAanKlikUit (KAKU)", "category": "remote", "desc": "Wireless switch"},
    {"id": 16, "name": "AlectoV1 Weather Sensor", "category": "weather", "desc": "Weather sensor (Alecto WS3500/WS4500)"},
    {"id": 17, "name": "Cardin S466-TX2", "category": "remote", "desc": "Remote control"},
    {"id": 18, "name": "Fine Offset Electronics WH2/WH5", "category": "weather", "desc": "Weather station"},
    {"id": 19, "name": "Nexus, FreeTec NC-7345, NX-3980", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 20, "name": "Ambient Weather F007TH, TFA 30.3208", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 21, "name": "Calibeur RF-104", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 22, "name": "X10 RF", "category": "remote", "desc": "Home automation"},
    {"id": 23, "name": "DSC Security Contact", "category": "security", "desc": "Security sensor"},
    {"id": 24, "name": "Brennenstuhl RCS 2044", "category": "remote", "desc": "Remote switch"},
    {"id": 25, "name": "Globaltronics GT-WT-02", "category": "temperature", "desc": "Wireless thermometer"},
    {"id": 26, "name": "Danfoss CFR Thermostat", "category": "appliance", "desc": "Thermostat"},
    {"id": 27, "name": "Energenie ENER010 (4-way)", "category": "remote", "desc": "Energy socket"},
    {"id": 28, "name": "Energenie MIHO009", "category": "remote", "desc": "Open sensor"},
    {"id": 29, "name": "Chuango Security Technology", "category": "security", "desc": "Security system"},
    {"id": 30, "name": "Generic Remote SC226x EV1527", "category": "remote", "desc": "Generic remote"},
    {"id": 31, "name": "TFA-Twin-Plus-30.3049", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 32, "name": "Fine Offset WH1080/WH3080", "category": "weather", "desc": "Weather station"},
    {"id": 33, "name": "WT450, WT260H, WT405H", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 34, "name": "LaCrosse WS-2310", "category": "weather", "desc": "Weather station"},
    {"id": 35, "name": "Esperanza EWS", "category": "weather", "desc": "Weather station"},
    {"id": 36, "name": "Efergy e2 classic", "category": "power", "desc": "Energy monitor"},
    {"id": 37, "name": "Inovalley kw9015b, TFA Dostmann 30.3161", "category": "temperature", "desc": "Temperature/rain sensor"},
    {"id": 38, "name": "Generic Temperature Sensor 1", "category": "temperature", "desc": "Generic temperature sensor"},
    {"id": 39, "name": "WG-PB12V1 Doorbell", "category": "doorbell", "desc": "Wireless doorbell"},
    {"id": 40, "name": "Acurite 592TXR Temp/Humidity", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 41, "name": "Acurite 986 Refrigerator/Freezer", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 42, "name": "HIDEKI TS04", "category": "weather", "desc": "Temp/humidity/wind/rain sensor"},
    {"id": 43, "name": "Watchman Sonic Oil Tank", "category": "other", "desc": "Oil tank level sensor"},
    {"id": 44, "name": "CurrentCost Current Sensor", "category": "power", "desc": "Energy monitor"},
    {"id": 45, "name": "emonTx OpenEnergyMonitor", "category": "power", "desc": "Energy monitor"},
    {"id": 46, "name": "HT680 Remote Control", "category": "remote", "desc": "Remote control"},
    {"id": 47, "name": "Conrad S3318P", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 48, "name": "Akhan 100F14 Remote", "category": "remote", "desc": "Remote keyless entry"},
    {"id": 49, "name": "Quhwa QH-C01B", "category": "doorbell", "desc": "Doorbell"},
    {"id": 50, "name": "OSv1 Temperature Sensor", "category": "temperature", "desc": "Oregon Scientific v1"},
    {"id": 51, "name": "Proove, Nexa, KlikAanKlikUit", "category": "remote", "desc": "Wireless switch"},
    {"id": 52, "name": "Bresser Thermo-/Hygro-Sensor 3CH", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 53, "name": "Springfield Temperature/Soil", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 54, "name": "Oregon Scientific SL109H", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 55, "name": "Digitech XC-0324 / AmbientWeather F007TH", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 56, "name": "Opus/Imagintronix XT300", "category": "temperature", "desc": "Soil moisture sensor"},
    {"id": 57, "name": "Infactory NC-3982-913", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 58, "name": "Hama TS33C/Bresser 5-in-1", "category": "weather", "desc": "Weather station"},
    {"id": 59, "name": "Bresser Weather Center 5-in-1", "category": "weather", "desc": "Weather station"},
    {"id": 60, "name": "Bresser Weather Center 6-in-1/7-in-1", "category": "weather", "desc": "Weather station"},
    {"id": 61, "name": "ELV/Renkforce E0001PA", "category": "weather", "desc": "Rain gauge"},
    {"id": 62, "name": "Eurochron EFTH-800", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 63, "name": "Auriol HG02832, Rubicson 48957", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 64, "name": "Fine Offset Electronics WH1080/WH3080 (FSK)", "category": "weather", "desc": "Weather station FSK"},
    {"id": 65, "name": "Honeywell ActivLink", "category": "security", "desc": "Security system"},
    {"id": 66, "name": "Maverick ET-732/733", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 67, "name": "RF-tech Remote", "category": "remote", "desc": "Remote control"},
    {"id": 68, "name": "LaCrosse TX141-Bv2/TX141TH-Bv2", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 69, "name": "Acurite 00275rm Temp/Humidity", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 70, "name": "LaCrosse TX35DTH-IT, TFA 30.3155", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 71, "name": "LaCrosse TX29IT", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 72, "name": "Vaillant calorMatic VRT340f", "category": "appliance", "desc": "Thermostat"},
    {"id": 73, "name": "Fine Offset WH25/WH32/WH65B", "category": "weather", "desc": "Weather station"},
    {"id": 74, "name": "Fine Offset WH0530 Temp/Rain", "category": "weather", "desc": "Temperature/rain sensor"},
    {"id": 75, "name": "IBIS Beacon", "category": "other", "desc": "IBIS beacon"},
    {"id": 76, "name": "Oil Watchman Standard", "category": "other", "desc": "Oil tank level sensor"},
    {"id": 77, "name": "Celsia CZC1 Thermostat", "category": "appliance", "desc": "Thermostat"},
    {"id": 78, "name": "Steelmate TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 79, "name": "Schrader TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 80, "name": "LightwaveRF", "category": "remote", "desc": "Home automation"},
    {"id": 81, "name": "Elro DB286A Doorbell", "category": "doorbell", "desc": "Wireless doorbell"},
    {"id": 82, "name": "Efergy Optical", "category": "power", "desc": "Energy monitor"},
    {"id": 83, "name": "Honda Car Key", "category": "automotive", "desc": "Car remote"},
    {"id": 84, "name": "Fine Offset Electronics WH51 Soil Moisture", "category": "weather", "desc": "Soil moisture sensor"},
    {"id": 85, "name": "Maverick XR-30 BBQ Sensor", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 86, "name": "SimpliSafe Home Security", "category": "security", "desc": "Security system"},
    {"id": 87, "name": "RF Power Meter Switch", "category": "power", "desc": "Power switch"},
    {"id": 88, "name": "Philips AJ3650 Outdoor Temp", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 89, "name": "Philips AJ7010 Outdoor Temp", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 90, "name": "KW9015B/ORIA Temp Sensor", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 91, "name": "Hyundai WS SENZOR 77TH", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 92, "name": "Radiohead ASK", "category": "other", "desc": "Generic ASK protocol"},
    {"id": 93, "name": "Kerui PIR/Contact Sensor", "category": "security", "desc": "PIR sensor"},
    {"id": 94, "name": "Fine Offset WH1050 Weather", "category": "weather", "desc": "Weather station"},
    {"id": 95, "name": "Honeywell CM921 Thermostat", "category": "appliance", "desc": "Thermostat"},
    {"id": 96, "name": "Hyundai TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 97, "name": "RojaFlex Shutter Motor", "category": "remote", "desc": "Shutter control"},
    {"id": 98, "name": "Somfy RTS", "category": "remote", "desc": "Shutter control"},
    {"id": 99, "name": "Schrader TPMS EG53MA4", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 100, "name": "Nexa/Proove Remote", "category": "remote", "desc": "Remote switch"},
    {"id": 101, "name": "AcuRite Grill/Meat Thermometer 01185M", "category": "temperature", "desc": "Meat thermometer"},
    {"id": 102, "name": "TFA Drop Rain Gauge 30.3233.01", "category": "weather", "desc": "Rain gauge"},
    {"id": 103, "name": "DSC Security (WS4945)", "category": "security", "desc": "Security contact"},
    {"id": 104, "name": "ERT Standard Consumption (SCM)", "category": "power", "desc": "Utility meter"},
    {"id": 105, "name": "Klimalogg Pro (TFA 30.3039)", "category": "temperature", "desc": "Temperature/humidity logger"},
    {"id": 106, "name": "Visonic Powercode Sensor", "category": "security", "desc": "Security sensor"},
    {"id": 107, "name": "Eurochron Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 108, "name": "ESIC EMT7110 Power Meter", "category": "power", "desc": "Power meter"},
    {"id": 109, "name": "Globaltronics QUIGG GT-TMBBQ-05", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 110, "name": "Dish Network 6.3 Remote", "category": "remote", "desc": "Remote control"},
    {"id": 111, "name": "SS S3318P, FreeTec NC-5849-913", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 112, "name": "Akhan 100F14", "category": "automotive", "desc": "Car remote"},
    {"id": 113, "name": "Quhwa QH-C01P", "category": "doorbell", "desc": "Doorbell"},
    {"id": 114, "name": "Oregon Scientific v1 Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 115, "name": "Proove/Nexa", "category": "remote", "desc": "Remote switch"},
    {"id": 116, "name": "Bresser Thermo-/Hygro 3CH", "category": "temperature", "desc": "Temperature/humidity"},
    {"id": 117, "name": "Springfield Soil Temperature", "category": "temperature", "desc": "Soil temperature"},
    {"id": 118, "name": "Oregon Scientific SL109H", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 119, "name": "Acurite 606TX Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 120, "name": "TFA Pool Thermometer 30.3053", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 121, "name": "Hemisphere GPS", "category": "other", "desc": "GPS receiver"},
    {"id": 122, "name": "Govee H5054 Water Leak", "category": "security", "desc": "Water leak detector"},
    {"id": 123, "name": "Fine Offset Electronics WH55", "category": "security", "desc": "Water leak sensor"},
    {"id": 124, "name": "BMW TPMS Gen2/Gen3", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 125, "name": "Toyota TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 126, "name": "Ford TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 127, "name": "Renault TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 128, "name": "PMV-107J TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 129, "name": "Elantra 2012 TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 130, "name": "Citroen TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 131, "name": "Jansite Solar TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 132, "name": "EezTire TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 133, "name": "Abarth 124 Spider TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 134, "name": "BMW Gen4-Gen5 TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 135, "name": "AVE TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 136, "name": "Sensor Line TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 137, "name": "Inkbird ITH-20R", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 138, "name": "Ambient Weather WH31E/EcoWitt WH40", "category": "weather", "desc": "Weather station"},
    {"id": 139, "name": "Maverick ET-732/733 BBQ", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 140, "name": "Ambient Weather WH31L Lightning", "category": "weather", "desc": "Lightning detector"},
    {"id": 141, "name": "Burnhard BBQ Thermometer", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 142, "name": "Auriol AFT 77 B2", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 143, "name": "Auriol 4-LD5661/4-LD5972", "category": "temperature", "desc": "Temperature/rain sensor"},
    {"id": 144, "name": "WS2032 Weather Station", "category": "weather", "desc": "Weather station"},
    {"id": 145, "name": "Auriol AHFL", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 146, "name": "Auriol AFW2A1", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 147, "name": "TFA Marbella Pool Thermometer", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 148, "name": "Auriol 4-LD6313", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 149, "name": "Conrad S3318P, ORIA WA50", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 150, "name": "Fine Offset WN34", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 151, "name": "Rubicson 48942 Pool Thermometer", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 152, "name": "Holman iWeather", "category": "weather", "desc": "Weather station"},
    {"id": 153, "name": "Bresser 6-in-1 Air Quality", "category": "weather", "desc": "Air quality sensor"},
    {"id": 154, "name": "EcoWitt WH45", "category": "weather", "desc": "Air quality sensor"},
    {"id": 155, "name": "Fine Offset WH43 Air Quality", "category": "weather", "desc": "Air quality sensor"},
    {"id": 156, "name": "Fine Offset WH46 Air Quality", "category": "weather", "desc": "Air quality sensor"},
    {"id": 157, "name": "Bresser Lightning", "category": "weather", "desc": "Lightning detector"},
    {"id": 158, "name": "Bresser Water Leakage", "category": "security", "desc": "Water leak sensor"},
    {"id": 159, "name": "Bresser Thermo-Hygro Explore", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 160, "name": "Cotech 36-7959 Weather Station", "category": "weather", "desc": "Weather station"},
    {"id": 161, "name": "Baldr Rain Gauge", "category": "weather", "desc": "Rain gauge"},
    {"id": 162, "name": "Baldr E0666TH", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 163, "name": "Biltema Rain Gauge", "category": "weather", "desc": "Rain gauge"},
    {"id": 164, "name": "Clipsal CMR113 Power Meter", "category": "power", "desc": "Power meter"},
    {"id": 165, "name": "DirecTV RC66RX Remote", "category": "remote", "desc": "Remote control"},
    {"id": 166, "name": "ERT Interval Data Message (IDM)", "category": "power", "desc": "Utility meter"},
    {"id": 167, "name": "ERT IDM for Net Meters", "category": "power", "desc": "Utility meter"},
    {"id": 168, "name": "Companion WTR001 Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 169, "name": "EnOcean ERP1", "category": "other", "desc": "EnOcean protocol"},
    {"id": 170, "name": "Blyss DC5-UK-WH", "category": "remote", "desc": "Remote switch"},
    {"id": 171, "name": "Kerui Smoke/Fire Detector", "category": "smoke", "desc": "Smoke detector"},
    {"id": 172, "name": "Chamberlain CWPIRC PIR", "category": "security", "desc": "PIR sensor"},
    {"id": 173, "name": "ESA1000/ESA2000 Energy Monitor", "category": "power", "desc": "Energy monitor"},
    {"id": 174, "name": "CED7000 Shot Timer", "category": "other", "desc": "Shot timer"},
    {"id": 175, "name": "DeltaDore X3D", "category": "remote", "desc": "Home automation"},
    {"id": 176, "name": "Cavius Smoke/Heat/Water Detector", "category": "smoke", "desc": "Multi-detector"},
    {"id": 177, "name": "EcoDHOME Smart Socket", "category": "power", "desc": "Smart socket"},
    {"id": 178, "name": "Arexx Multilogger", "category": "temperature", "desc": "Temperature logger"},
    {"id": 179, "name": "Atech-WS308 Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 180, "name": "TBH Weather Sensor", "category": "weather", "desc": "Weather sensor"},
    {"id": 181, "name": "Apator Metra E-RM 30", "category": "water", "desc": "Water meter"},
    {"id": 182, "name": "Arad/Master Meter Dialog3G", "category": "water", "desc": "Water meter"},
    {"id": 183, "name": "ANT and ANT+ Devices", "category": "other", "desc": "ANT+ protocol"},
    {"id": 184, "name": "Ecowitt WH53/WH0280/WH0281A", "category": "temperature", "desc": "Outdoor thermometer"},
    {"id": 185, "name": "Emax W6 Weather Station", "category": "weather", "desc": "Weather station"},
    {"id": 186, "name": "EMOS E6016 Rain Gauge", "category": "weather", "desc": "Rain gauge"},
    {"id": 187, "name": "EMOS E6016 Weather Station (DCF77)", "category": "weather", "desc": "Weather station"},
    {"id": 188, "name": "Emos TTX201 Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 189, "name": "Ambient Weather TX-8300", "category": "temperature", "desc": "Temperature/humidity sensor"},
    {"id": 190, "name": "Amazon Basics Meat Thermometer", "category": "temperature", "desc": "Meat thermometer"},
    {"id": 191, "name": "Badger ORION Water Meter (100k)", "category": "water", "desc": "Water meter"},
    {"id": 192, "name": "Badger ORION Water Meter (GIF)", "category": "water", "desc": "Water meter"},
    {"id": 193, "name": "Badger ORION Water Meter (GIF2020)", "category": "water", "desc": "Water meter"},
    {"id": 194, "name": "BlueLine PowerCost Monitor", "category": "power", "desc": "Power monitor"},
    {"id": 195, "name": "bm5-v2 12V Battery Monitor", "category": "automotive", "desc": "Battery monitor"},
    {"id": 196, "name": "Flexcon Reglera PC320", "category": "appliance", "desc": "Heating control"},
    {"id": 197, "name": "FlexCon Pool Thermometer", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 198, "name": "Flowis Flow Meter", "category": "water", "desc": "Flow meter"},
    {"id": 199, "name": "General Electric Color Effects", "category": "other", "desc": "LED controller"},
    {"id": 200, "name": "Generic Temperature Sensor", "category": "temperature", "desc": "Generic sensor"},
    {"id": 201, "name": "Geo Minim+ Energy Monitor", "category": "power", "desc": "Energy monitor"},
    {"id": 202, "name": "Govee Water Leak Detector", "category": "security", "desc": "Water leak sensor"},
    {"id": 203, "name": "GT-WT-03 Weather Station", "category": "weather", "desc": "Weather station"},
    {"id": 204, "name": "Hager TRC200 Remote", "category": "remote", "desc": "Remote control"},
    {"id": 205, "name": "Holman WS5029 Weather Station", "category": "weather", "desc": "Weather station"},
    {"id": 206, "name": "Honeywell 2Gig HIK2-345", "category": "security", "desc": "Security sensor"},
    {"id": 207, "name": "Honeywell 5800 Series", "category": "security", "desc": "Security sensor"},
    {"id": 208, "name": "Honeywell HGI80", "category": "appliance", "desc": "Thermostat"},
    {"id": 209, "name": "Honeywell Wireless Doorbell", "category": "doorbell", "desc": "Doorbell"},
    {"id": 210, "name": "Insteon Devices", "category": "remote", "desc": "Home automation"},
    {"id": 211, "name": "inFactory NC-3982-913", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 212, "name": "interlogix/GE Security", "category": "security", "desc": "Security sensor"},
    {"id": 213, "name": "Jasco/GE Wireless Doorbell", "category": "doorbell", "desc": "Doorbell"},
    {"id": 214, "name": "Kerui D026 Door Sensor", "category": "security", "desc": "Door sensor"},
    {"id": 215, "name": "Lacrosse Breezepro TX Sensor", "category": "weather", "desc": "Wind sensor"},
    {"id": 216, "name": "LaCrosse TX141W", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 217, "name": "LaCrosse Technology View", "category": "weather", "desc": "Weather station"},
    {"id": 218, "name": "LaCrosse TX141TH-Bv3", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 219, "name": "LaCrosse WS-1650", "category": "weather", "desc": "Weather station"},
    {"id": 220, "name": "LaCrosse WS-7000", "category": "weather", "desc": "Weather station"},
    {"id": 221, "name": "Markisol Shutter Remote", "category": "remote", "desc": "Shutter control"},
    {"id": 222, "name": "Microchip HCS200/HCS300", "category": "automotive", "desc": "Car remote"},
    {"id": 223, "name": "Missil ML0757 BBQ Thermometer", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 224, "name": "Neptune R900 Water Meter", "category": "water", "desc": "Water meter"},
    {"id": 225, "name": "Nice Flor-s Remote", "category": "remote", "desc": "Gate remote"},
    {"id": 226, "name": "Norgo NGE101", "category": "power", "desc": "Energy monitor"},
    {"id": 227, "name": "Oil Ultrasonic Tank Gauge", "category": "other", "desc": "Tank level sensor"},
    {"id": 228, "name": "Omron Wireless BP Monitor", "category": "other", "desc": "Blood pressure monitor"},
    {"id": 229, "name": "OPUS/Imagintronix Soil Moisture", "category": "weather", "desc": "Soil moisture"},
    {"id": 230, "name": "Oregon THGR122N", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 231, "name": "Oregon THGR810", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 232, "name": "Oregon THGR968", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 233, "name": "Oregon THN132N", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 234, "name": "Philips Outdoor Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 235, "name": "Quinetic Door Switch", "category": "remote", "desc": "Door switch"},
    {"id": 236, "name": "Revolt NC-5462", "category": "power", "desc": "Power meter"},
    {"id": 237, "name": "Rosstech Digital Tire Gauge", "category": "tpms", "desc": "Tire pressure gauge"},
    {"id": 238, "name": "Rubicson Pool Thermometer", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 239, "name": "Schou 72543 Pool Thermometer", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 240, "name": "Secplus v1 Door Sensor", "category": "security", "desc": "Door sensor"},
    {"id": 241, "name": "Secplus v2 Door Sensor", "category": "security", "desc": "Door sensor"},
    {"id": 242, "name": "Sharp SPC775 Weather Station", "category": "weather", "desc": "Weather station"},
    {"id": 243, "name": "Skylink HA-100/GT-100 Remote", "category": "remote", "desc": "Remote control"},
    {"id": 244, "name": "Smith Scale", "category": "other", "desc": "Weight scale"},
    {"id": 245, "name": "Smoke Detector GS558", "category": "smoke", "desc": "Smoke detector"},
    {"id": 246, "name": "Somfy IOHC", "category": "remote", "desc": "Shutter control"},
    {"id": 247, "name": "SRSmith Pool Light Remote", "category": "remote", "desc": "Pool light"},
    {"id": 248, "name": "Standard Consumption (SCMplus)", "category": "power", "desc": "Utility meter"},
    {"id": 249, "name": "Steelmate SK-539", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 250, "name": "SwitchDoc Labs SM23 Soil", "category": "weather", "desc": "Soil moisture sensor"},
    {"id": 251, "name": "TechnoLine WS2085", "category": "weather", "desc": "Weather station"},
    {"id": 252, "name": "Telldus Door/Window Sensor", "category": "security", "desc": "Door/window sensor"},
    {"id": 253, "name": "Telldus Fineoffset", "category": "weather", "desc": "Weather station"},
    {"id": 254, "name": "Tesla Tire Pressure Monitor", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 255, "name": "TFA Dostmann 30.3196", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 256, "name": "TFA Dostmann 30.3221.02", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 257, "name": "TFA Dostmann 30.3222.02", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 258, "name": "TFA Dostmann 30.3228.02", "category": "weather", "desc": "Rain sensor"},
    {"id": 259, "name": "TFA Dostmann 14.1504.V2", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 260, "name": "Thermopro TP11 BBQ", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 261, "name": "Thermopro TP12 BBQ", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 262, "name": "Thermopro TP20 BBQ", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 263, "name": "ThermoPro TP28b BBQ", "category": "temperature", "desc": "BBQ thermometer"},
    {"id": 264, "name": "Thermopro TX-2 Pool", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 265, "name": "THN128, THN138 Temp Sensor", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 266, "name": "TS-FT002 Wireless Ultrasonic", "category": "other", "desc": "Tank level sensor"},
    {"id": 267, "name": "UPM/Esic Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 268, "name": "Valeo TPMS", "category": "tpms", "desc": "Tire pressure monitor"},
    {"id": 269, "name": "Vevor Wireless Pool Thermometer", "category": "temperature", "desc": "Pool thermometer"},
    {"id": 270, "name": "Viking 02035/02038 Click Remote", "category": "remote", "desc": "Remote switch"},
    {"id": 271, "name": "Visonic Powercode Door/Window", "category": "security", "desc": "Door/window sensor"},
    {"id": 272, "name": "Watts WFHT-RF Thermostat", "category": "appliance", "desc": "Thermostat"},
    {"id": 273, "name": "Waveman YT-400", "category": "remote", "desc": "Remote switch"},
    {"id": 274, "name": "Wendox W6726", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 275, "name": "Wireless M-Bus (mode C&T)", "category": "other", "desc": "Utility meter"},
    {"id": 276, "name": "WS Temperature Sensor", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 277, "name": "X10 Security", "category": "security", "desc": "Security sensor"},
    {"id": 278, "name": "Yale Smart Lock", "category": "security", "desc": "Smart lock"},
    {"id": 279, "name": "Yale HSA Series", "category": "security", "desc": "Security system"},
    {"id": 280, "name": "Yardforce Robot Mower", "category": "other", "desc": "Robot mower"},
    {"id": 281, "name": "ZORTRAX HEATER", "category": "appliance", "desc": "3D printer heater"},
    {"id": 282, "name": "Acurite 590TX Temperature", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 283, "name": "Fine Offset WH32B Sensor", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 284, "name": "Kedsum Wireless Thermometer", "category": "temperature", "desc": "Temperature sensor"},
    {"id": 285, "name": "Marlec Solar iBoost+", "category": "power", "desc": "Solar monitor"},
    {"id": 286, "name": "Oil Depot SD-200", "category": "other", "desc": "Tank level sensor"},
    {"id": 287, "name": "Oregon Scientific v2.1", "category": "weather", "desc": "Weather station"},
    {"id": 288, "name": "Oregon Scientific v3", "category": "weather", "desc": "Weather station"},
    {"id": 289, "name": "Regency Ceiling Fan Remote", "category": "remote", "desc": "Fan remote"},
    {"id": 290, "name": "Sensible Living Wireless Water", "category": "water", "desc": "Water meter"},
    {"id": 291, "name": "Wireless S7 Doorbell", "category": "doorbell", "desc": "Doorbell"},
]


# RTL-433 program flags
PROGRAM_FLAGS = [
    {
        "flag": "-f",
        "name": "frequency",
        "type": "text",
        "default": "433.92M",
        "desc": "Receive frequency (e.g., 433.92M, 315M, 868M)",
        "examples": ["433.92M", "315M", "868M", "915M"]
    },
    {
        "flag": "-s",
        "name": "sample_rate",
        "type": "text",
        "default": "1024k",
        "desc": "Sample rate (e.g., 250k, 1024k, 2048k)",
        "examples": ["250k", "1024k", "2048k", "3200k"]
    },
    {
        "flag": "-g",
        "name": "gain",
        "type": "number",
        "default": 40,
        "min": 0,
        "max": 50,
        "desc": "Tuner gain (0-50 dB, or 'auto')"
    },
    {
        "flag": "-p",
        "name": "ppm_error",
        "type": "number",
        "default": 0,
        "min": -100,
        "max": 100,
        "desc": "Frequency correction in ppm"
    },
    {
        "flag": "-R",
        "name": "protocol",
        "type": "protocol",
        "default": [],
        "desc": "Enable specific protocol decoder(s)"
    },
    {
        "flag": "-G",
        "name": "protocol_all",
        "type": "boolean",
        "default": False,
        "desc": "Enable all protocol decoders"
    },
    {
        "flag": "-X",
        "name": "flex_decoder",
        "type": "text",
        "default": "",
        "desc": "Add a custom flex decoder"
    },
    {
        "flag": "-A",
        "name": "analyze",
        "type": "boolean",
        "default": False,
        "desc": "Analyze pulses (debug mode)"
    },
    {
        "flag": "-v",
        "name": "verbose",
        "type": "boolean",
        "default": False,
        "desc": "Verbose output"
    },
    {
        "flag": "-C",
        "name": "convert",
        "type": "select",
        "default": "si",
        "options": ["si", "customary", "native"],
        "desc": "Convert units (si=metric, customary=imperial)"
    },
    {
        "flag": "-n",
        "name": "limit",
        "type": "number",
        "default": 0,
        "desc": "Stop after receiving n signals (0=unlimited)"
    },
    {
        "flag": "-T",
        "name": "duration",
        "type": "number",
        "default": 0,
        "desc": "Run for n seconds (0=unlimited)"
    },
    {
        "flag": "-F",
        "name": "output",
        "type": "multiselect",
        "default": ["json"],
        "options": ["json", "csv", "kv", "mqtt", "influx", "syslog", "null"],
        "desc": "Output format(s)"
    },
    {
        "flag": "-M",
        "name": "metadata",
        "type": "multiselect",
        "default": [],
        "options": ["time", "reltime", "notime", "hires", "utc", "protocol", "level", "stats", "bits"],
        "desc": "Add metadata to output"
    },
    {
        "flag": "-r",
        "name": "read_file",
        "type": "text",
        "default": "",
        "desc": "Read signals from file instead of RTL-SDR"
    },
    {
        "flag": "-w",
        "name": "write_file",
        "type": "text",
        "default": "",
        "desc": "Save raw signal data to file"
    },
    {
        "flag": "-Y",
        "name": "autolevel",
        "type": "select",
        "default": "auto",
        "options": ["auto", "minmax", "magest", "off"],
        "desc": "Auto-leveling algorithm"
    },
    {
        "flag": "-H",
        "name": "hop_time",
        "type": "number",
        "default": 0,
        "desc": "Frequency hop time in seconds (0=disabled)"
    },
]


def get_protocols_by_category() -> Dict[str, List[Dict[str, Any]]]:
    """Get protocols grouped by category."""
    result = {}
    for proto in PROTOCOLS:
        cat = proto["category"]
        if cat not in result:
            result[cat] = []
        result[cat].append(proto)
    return result


def search_protocols(query: str) -> List[Dict[str, Any]]:
    """Search protocols by name or description."""
    query = query.lower()
    return [
        p for p in PROTOCOLS
        if query in p["name"].lower() or query in p.get("desc", "").lower()
    ]
